### ISSUE TITLE
Gepard does not work

### ISSUE THREAD

**Issue by manighanipoor** [univieCUBE/gepard#10]
I installed new version of Gepard by conda in Ubuntu and ran a test using two short sequence fasta files (seq1.fasta and seq2.fasta) and "-matrix edna.mat" as the substitution matrix (I got "edna.mat" file from "https://github.com/univieCUBE/gepard/blob/master/src/matrices/edna.mat"). Here is my command:
gepardcmd -seq seq1.fasta seq2.fasta -matrix edna.mat -word 7 -format jpg -outfile plot.jpg

Here is seq1.fasta file:

>SRR10418058.1 1 length=6361
TTGTTGGCCTTCGTTCAGTTACATGTGTGCTGGCAGGACAGGAGTTCAGAGGTTCAGTCAAGAGAGGTTTCTTTCTTTCCTCCAGGCTTTCAGGAGGAGATTCCAAGCAGCCTCCGGCTCGAGGCTCTATAGGCTGAAACAGGCCCATTCCCACGCCCCTTCCTGAAATCCCAGGAGATCCATTTTTGCCCTGAGGCACTCTGCAGTGCCTTGCACACTTACCTGCTCCAAAAGCGGGCCGCGTGGGGACTCCTGGGATTGGTGGGGTGGGGTGGGCGGCGGACTGCAGAGTTCTGGTCTTTTGCAGAATCTTAGCTGAGGGGCTATCTCCAGAGCCCTGCAAACCCCCCAGCAGGCCACCCCTGCCCGTACCTGTAACAATAAAATAAACCACTACTATTGGTACGTGTCTCTCTGAGGTTCCTAGCCCATTGGCAAAACCACTTATCTTAGGATGTTTTTGAAAGTGTATCAGGTGGAGAGCTAGCGTTGTCTCCCATGATGTTATTCTGTAGGCTGGGAGCCACTACAGAAAGGCCTTCTTCTCCTTCTAGATGAACCTCTTATATCTCATTGATATTTATGTCATTGCTTATCTCCAAAGTTGCATGCCTGCCTGTCAAACATATAAATAAGATTATTTCTAATTCAGACTCCGATTAATACAAAATAATTCCAAATATCAAAAAGTACTTACCCCCCCAAAAAAAAATCTTAGAA

and here is seq2.fasta file:

>SRR10418058.4 4 length=5734
ATGTTTTGTCAGGGGGTTCCAGTCAGAGAGGTTCCTAAAATGGTGAAGTTACCTTACCTCGCCACTTCCTGGTCAGCACTGCTATGGATGTGTAGCCACTCTGCACATGGTGGTGGCGTCACAACTGCCAGTGCTGAACGAAAAGCCATGCCATATGAAAGTTTTGCAGCTATCAGGCCTGAAAGAAAAGAACCAAGGAACTTGGATCCACTGTATGGACTAAGCTGGCTTCTGGTTTGTCCAGAAAAGATAAAGTTGACTTCTCAAGTGACTCAGTTTTGGTGGCAAGCCATAAAAGGATATGATCTTGTTCATATTTATTCATGATTCTCAGGGTCACAACCCACAGGTTTGAGAGATCCTCACTGCAAGTTTCCCAGTGATGAAGTGAAAAAGAATGATACACAGCATGCTGAATAATGCACCGGTAAGTGGCTAGCATTGTTCCCCCATCCCAACAGTTAAGTGCCAAGGTTTAGCAGTCTATGGAGACTTCAAGGTTGCTACTCCAGTTATTGGCACCTTCCTGACAATATGCAGATTGACATAACATTTCCTCAGTTTCTCCCTAATAAGTAGATAGTGCTAATCAAAATACCAGATCAGACAGGCATTTAAAGTAGCTGGGTATATGTAAATGCTATTAGTCAGGTGTTACAGTTGTTAAAATACTTTTCATTTGAATTGGTCAAGGAGCATATTTCTTACTATCTTCCAGGTGAGGTAAAGGTGAAACTACAATCACATTAATAAAATATACAAAATTAATGAATGGCTTTTTTTTAAAAAGCTAGGATGGGAAATAGGTTAGAGGGAGCAGTAAGATATGACAAAAGAAAGAAAGGGAGTCTCTCTTTTCTCCTGCTTTTTCTTCTGTTGCCTCCTATAGAATGATCCTGA

Could you please let me know why it did not work?

Cheers,
Mani

**Comment by JulleeeK** [comment]
Dear Mani,

When I tested it, it threw the error "invalid fasta file", which, in this case, was thrown because the symbol ">" is missing in front of the line "SRR10418058.1 1 length=6361" (and the equivalent line in the other sequence). In fasta files, status/comment lines are always premised by it.

I hope I could help.
best,
Julius
