### ISSUE TITLE
It will be great if gepard can output images in pdf/svg format

### ISSUE THREAD

**Issue by yjx1217** [univieCUBE/gepard#2]
Hello,

I really like gepard and use it in my work a lot. I was wondering if the developer can add the functionality of generating pdf/svg image in addition to current supported formats (jpeg, bmp, png). Thanks for consideration!

Best,
Jia-Xing

**Comment by rattei** [comment]
Sorry for the extremely long delay. We now continue the development of gepard, so this issue will now be addressed.

**Comment by yjx1217** [comment]
Thx! That's awesome! Looking forward to the new version!

**Comment by yjx1217** [comment]
Great! Thanks for the efforts, Julius!

Best,
Jia-Xing
