### ISSUE TITLE
Make a 1.40 official release

### ISSUE THREAD

**Issue by tseemann** [univieCUBE/gepard#3]
For packaging in Brew/Conda can you please make a release?

**Comment by rattei** [comment]
Hi Torsten,
have created a release v1.40.0 now.
Best regards, Thomas

**Comment by tseemann** [comment]
Thanks @rattei !

**Comment by Juke34** [comment]
As it was not yet in bioconda I have added the recipe (PR merged today so will be available soon).
The command to run it in graphical mode is:   
`gepard`
and to run in command line mode type:   
`gepardcmd`

**Comment by tseemann** [comment]
I did package it Brew - never got to Conda sorry!
