### ISSUE TITLE
output alignment as well

### ISSUE THREAD

**Issue by zy041225** [univieCUBE/gepard#4]
Hi,

I'm using gepard to generate dotplots and it works great. However, I wonder if I can also get the alignment position on each sequence so that I can also check sequence features on some alignment (e.g. if it's a repeat or not, and what kind of repeat it is)

Best,
Yang

**Comment by rattei** [comment]
Thanks for the suggession. We will put it on our list. As there is currently no further active development of gepard, I cannot tell you when the function might be implemented.

best,
Thomas

**Comment by zy041225** [comment]
Hi Thomas,

Thanks for the reply. do you have any suggestion about which software can do this kind of work for me? I've tried several (including mummerplot (mummer), dottermatcher, etc). Mummer indeed provide alignment, but I suspect the alignment algorithm is different from gepard since its plot contains less alignment than gepard.

Best,
Yang

**Comment by rattei** [comment]
Hi Yang,
gepard is not an alignment program at all. It is a dotplot visualization tool. Given two positions in the set of sequences (according to your selection in the dotplot), it just displays the two sequences from these positions.

Best,
Thomas

**Comment by rattei** [comment]
We now continue to work on gepard, so we will also address this issue.
