### ISSUE TITLE
matrices

### ISSUE THREAD

**Issue by duhuipeng** [univieCUBE/gepard#7]
Dear author
My code is as follows
java -cp dist/Gepard-1.40.jar org.gepard.client.cmdline.CommandLine -seq1 ../bmxchrX_seqkit.fa -seq2 ../chrX_seqkit.fa -matrix resources/matrices/edna.mat -word 500 -window 1 -lower 95 -outfile gepard_ref1_vs_ref2_1.png
my result as follow
![image](https://user-images.githubusercontent.com/58722433/146858312-d8d12b1b-3bc8-4d62-9f24-ec77604a5329.png)
But the human article I refer to is as follows
![image](https://user-images.githubusercontent.com/58722433/146858392-b01fac17-34c1-4ccd-9b73-9b5aecb5f922.png)
I'm basically all the same result in the article except for the matrice parameter, can you tell if the question of my matrix parameters, I should have an alignment of such centromeric regions,
How to set the matrix parameters to show the article

Best
HUipengDU

**Comment by rattei** [comment]
Display parameters can be adjusted using the command line parameters -lower, -upper, -greyscale. Please make use of these parameters.

**Comment by rattei** [comment]
You might have missed the fact that gepard provides a graphical user interface. One of its use cases is the visual adjustment of display parameters, for later use on the commandline. We strongly recommend the use of the GUI to find the optimal parameters in this case.
